# Generated by Django 4.0.5 on 2022-07-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='categoria',
            field=models.CharField(choices=[('ANALISES', 'Análises'), ('APRESENTACAO', 'Apresentação'), ('PROGRAMACAO', 'Programação'), ('COMEDIA', 'Comedia'), ('DRAMA', 'Drama'), ('TERROR', 'Terror'), ('SUSPENSE', 'Suspense'), ('FICCAO', 'Ficção'), ('ANIMACAO', 'Animação'), ('ACAO', 'Ação'), ('AVENTURA', 'Aventura'), ('OUTROS', 'Outros')], max_length=15),
        ),
    ]
